apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: click-app
  template:
    metadata:
      labels:
        app: click-app
    spec:
      containers:
        - name: click-app
          image: your-docker-username/click-app:latest  # Replace with your Docker Hub image
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: click-app-service
spec:
  type: NodePort
  selector:
    app: click-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30007  # Minikube exposes it on this port

